export const API_ENDPOINTS = {
  BASE_URL: "https://api.dub.co",
  ANALYTICS_GET: "/analytics",
  COMMISSIONS_GET_ALL: "/commissions",
  COMMISSIONS_UPDATE: (id: string) => `/commissions/${id}`,
  CONVERSIONS_TRACK_LEAD: "/track/lead",
  CONVERSIONS_TRACK_SALE: "/track/sale",
  CUSTOMERS_DELETE: (id: string) => `/customers/${id}`,
  CUSTOMERS_GET: (id: string) => `/customers/${id}`,
  CUSTOMERS_GET_ALL: "/customers",
  CUSTOMERS_UPDATE: (id: string) => `/customers/${id}`,
  DOMAINS_CREATE: "/domains",
  DOMAINS_DELETE: (slug: string) => `/domains/${slug}`,
  DOMAINS_GET: (slug: string) => `/domains/${slug}`,
  DOMAINS_UPDATE: (slug: string) => `/domains/${slug}`,
  FOLDERS_CREATE: "/folders",
  FOLDERS_DELETE: (folderId: string) => `/folders/${folderId}`,
  FOLDERS_GET: (folderId: string) => `/folders/${folderId}`,
  FOLDERS_UPDATE: (folderId: string) => `/folders/${folderId}`,
  LINKS_BULK_CREATE: "/links/bulk",
  LINKS_BULK_DELETE: "/links/bulk",
  LINKS_BULK_UPDATE: "/links/bulk",
  LINKS_CREATE: "/links",
  LINKS_DELETE: (linkId: string) => `/links/${linkId}`,
  LINKS_GET: "/links/info",
  LINKS_GET_ALL: "/links",
  LINKS_UPDATE: (linkId: string) => `/links/${linkId}`,
  LINKS_UPSERT: "/links/upsert",
  PARTNERS_CREATE: "/partners",
  PARTNERS_GET: "/partners",
  PARTNERS_GET_ALL: "/partners",
  PARTNERS_UPDATE: "/partners",
  TAGS_CREATE: "/tags",
  TAGS_GET_ALL: "/tags",
  TAGS_UPDATE: (id: string) => `/tags/${id}`,
};
